/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, Record<string, any>> = {
  wuhan: {
    button: {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/button.tsx",
          type: "registry:ui",
          target: "components/ui/button.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/button.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    collapsible: {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/collapsible.tsx",
          type: "registry:ui",
          target: "components/ui/collapsible.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/collapsible.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    separator: {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/separator.tsx",
          type: "registry:ui",
          target: "components/ui/separator.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/separator.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    textarea: {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/textarea.tsx",
          type: "registry:ui",
          target: "components/ui/textarea.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/textarea.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    tooltip: {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/tooltip.tsx",
          type: "registry:ui",
          target: "components/ui/tooltip.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/tooltip.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    card: {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/card.tsx",
          type: "registry:ui",
          target: "components/ui/card.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/card.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    dialog: {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/dialog.tsx",
          type: "registry:ui",
          target: "components/ui/dialog.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/dialog.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    drawer: {
      name: "drawer",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/drawer.tsx",
          type: "registry:ui",
          target: "components/ui/drawer.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/drawer.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    tabs: {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/wuhan/ui/tabs.tsx",
          type: "registry:ui",
          target: "components/ui/tabs.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/ui/tabs.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "hello-world": {
      name: "hello-world",
      description: "A simple hello world component",
      type: "registry:block",
      registryDependencies: ["style", "button"],
      files: [
        {
          path: "registry/wuhan/blocks/hello-world/hello-world.tsx",
          type: "registry:component",
          target: "components/wuhan/components/hello-world.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/hello-world/hello-world.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-01": {
      name: "message-01",
      description: "AI and user message components",
      type: "registry:block",
      registryDependencies: ["style", "button"],
      files: [
        {
          path: "registry/wuhan/blocks/message/message-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/message-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/message/message-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-01": {
      name: "quick-action-01",
      description:
        "Quick action button components for suggestions and next step guidance (Base Block)",
      type: "registry:block",
      registryDependencies: ["style", "button"],
      files: [
        {
          path: "registry/wuhan/blocks/quick-action/quick-action-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/quick-action-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/quick-action/quick-action-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-01": {
      name: "prompt-01",
      description: "Prompt button (horizontal layout)",
      type: "registry:block",
      registryDependencies: ["style", "quick-action-01"],
      files: [
        {
          path: "registry/wuhan/blocks/prompt/prompt-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/prompt-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/prompt/prompt-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-02": {
      name: "prompt-02",
      description: "Prompt button (vertical layout)",
      type: "registry:block",
      registryDependencies: ["style", "quick-action-01"],
      files: [
        {
          path: "registry/wuhan/blocks/prompt/prompt-02.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/prompt-02.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/prompt/prompt-02.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "suggestion-01": {
      name: "suggestion-01",
      description:
        "Suggestion button for next step guidance (text first, icon last)",
      type: "registry:block",
      registryDependencies: ["style", "quick-action-01"],
      files: [
        {
          path: "registry/wuhan/blocks/suggestion/suggestion-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/suggestion-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/suggestion/suggestion-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-01": {
      name: "sender-01",
      description: "Message sender component",
      type: "registry:block",
      registryDependencies: ["style", "textarea", "button"],
      files: [
        {
          path: "registry/wuhan/blocks/sender/sender-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/sender-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/sender/sender-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "attachment-list-01": {
      name: "attachment-list-01",
      description: "Attachment list component",
      type: "registry:block",
      registryDependencies: ["style", "button"],
      files: [
        {
          path: "registry/wuhan/blocks/attachment-list/attachment-list-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/attachment-list-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/attachment-list/attachment-list-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "avatar-header-01": {
      name: "avatar-header-01",
      description: "Message avatar header component (avatar + name + time)",
      type: "registry:block",
      registryDependencies: ["style"],
      files: [
        {
          path: "registry/wuhan/blocks/avatar-header/avatar-header-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/avatar-header-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/avatar-header/avatar-header-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "history-item-01": {
      name: "history-item-01",
      description:
        "History record list item component (default/hover/selected)",
      type: "registry:block",
      registryDependencies: ["style"],
      files: [
        {
          path: "registry/wuhan/blocks/history-item/history-item-01.tsx",
          type: "registry:component",
          target: "components/wuhan/blocks/history-item-01.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/blocks/history-item/history-item-01.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-demo": {
      name: "message-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-default": {
      name: "message-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-default.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-default.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-default.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-composed-demo": {
      name: "message-composed-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01", "button"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-composed-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-composed-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-composed-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-with-status": {
      name: "message-with-status",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01", "button"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-with-status.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-with-status.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-with-status.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-with-attachment": {
      name: "message-with-attachment",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01", "attachment-list-01"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-with-attachment.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-with-attachment.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-with-attachment.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-with-feedback": {
      name: "message-with-feedback",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01", "button"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-with-feedback.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-with-feedback.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-with-feedback.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "message-with-avatar-header": {
      name: "message-with-avatar-header",
      description: "",
      type: "registry:example",
      registryDependencies: ["message-01", "avatar-header-01"],
      files: [
        {
          path: "registry/wuhan/examples/message/message-with-avatar-header.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/message-with-avatar-header.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/message/message-with-avatar-header.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "attachment-list-demo": {
      name: "attachment-list-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["attachment-list-01"],
      files: [
        {
          path: "registry/wuhan/examples/attachment-list/attachment-list-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/attachment-list-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/attachment-list/attachment-list-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "avatar-header-demo": {
      name: "avatar-header-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar-header-01"],
      files: [
        {
          path: "registry/wuhan/examples/avatar-header/avatar-header-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/avatar-header-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/avatar-header/avatar-header-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "history-item-demo": {
      name: "history-item-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["history-item-01", "tooltip"],
      files: [
        {
          path: "registry/wuhan/examples/history-item/history-item-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/history-item-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/history-item/history-item-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-demo": {
      name: "sender-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sender-01"],
      files: [
        {
          path: "registry/wuhan/examples/sender/sender-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/sender-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/sender/sender-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-default": {
      name: "sender-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["sender-01"],
      files: [
        {
          path: "registry/wuhan/examples/sender/sender-default.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/sender-default.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/sender/sender-default.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-active": {
      name: "sender-active",
      description: "",
      type: "registry:example",
      registryDependencies: ["sender-01"],
      files: [
        {
          path: "registry/wuhan/examples/sender/sender-active.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/sender-active.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/sender/sender-active.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-disabled": {
      name: "sender-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["sender-01"],
      files: [
        {
          path: "registry/wuhan/examples/sender/sender-disabled.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/sender-disabled.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/sender/sender-disabled.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "sender-composed-demo": {
      name: "sender-composed-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["sender-01", "attachment-list-01"],
      files: [
        {
          path: "registry/wuhan/examples/sender/sender-composed-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/sender-composed-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/sender/sender-composed-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [
        {
          path: "registry/wuhan/examples/textarea/textarea-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/textarea-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/textarea/textarea-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/wuhan/examples/button/button-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/button-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/button/button-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-demo": {
      name: "prompt-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt-01", "prompt-02"],
      files: [
        {
          path: "registry/wuhan/examples/prompt/prompt-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/prompt-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/prompt/prompt-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-horizontal": {
      name: "prompt-horizontal",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt-01"],
      files: [
        {
          path: "registry/wuhan/examples/prompt/prompt-horizontal.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/prompt-horizontal.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/prompt/prompt-horizontal.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-vertical": {
      name: "prompt-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt-02"],
      files: [
        {
          path: "registry/wuhan/examples/prompt/prompt-vertical.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/prompt-vertical.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/prompt/prompt-vertical.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "suggestion-demo": {
      name: "suggestion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["suggestion-01"],
      files: [
        {
          path: "registry/wuhan/examples/suggestion/suggestion-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/suggestion-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/suggestion/suggestion-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "suggestion-default": {
      name: "suggestion-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["suggestion-01"],
      files: [
        {
          path: "registry/wuhan/examples/suggestion/suggestion-default.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/suggestion-default.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/suggestion/suggestion-default.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "suggestion-custom-icon": {
      name: "suggestion-custom-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["suggestion-01"],
      files: [
        {
          path: "registry/wuhan/examples/suggestion/suggestion-custom-icon.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/suggestion-custom-icon.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/suggestion/suggestion-custom-icon.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-demo": {
      name: "quick-action-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-demo.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-demo.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-default": {
      name: "quick-action-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-default.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-default.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-default.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-with-icons": {
      name: "quick-action-with-icons",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-with-icons.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-with-icons.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-with-icons.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-single": {
      name: "quick-action-single",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-single.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-single.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-single.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-interactive": {
      name: "quick-action-interactive",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-interactive.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-interactive.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-interactive.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-disabled": {
      name: "quick-action-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-disabled.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-disabled.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-disabled.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "quick-action-flexible-layout": {
      name: "quick-action-flexible-layout",
      description: "",
      type: "registry:example",
      registryDependencies: ["quick-action-01"],
      files: [
        {
          path: "registry/wuhan/examples/quick-action/quick-action-flexible-layout.tsx",
          type: "registry:example",
          target: "components/wuhan/examples/quick-action-flexible-layout.tsx",
        },
      ],
      component: React.lazy(async () => {
        const mod =
          await import("@/registry/wuhan/examples/quick-action/quick-action-flexible-layout.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
  },
};
