// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, Record<string, any>> = {
  wuhan: {
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/wuhan/examples/button-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/button-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [
        {
          path: "registry/wuhan/examples/textarea-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/textarea-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-demo": {
      name: "prompt-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt"],
      files: [
        {
          path: "registry/wuhan/examples/prompt-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-demo.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-active": {
      name: "prompt-active",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt"],
      files: [
        {
          path: "registry/wuhan/examples/prompt-active.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/wuhan/examples/prompt-active.tsx");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-default": {
      name: "prompt-default",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt"],
      files: [
        {
          path: "registry/wuhan/examples/prompt-default.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/wuhan/examples/prompt-default.tsx"
        );
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
    "prompt-disabled": {
      name: "prompt-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["prompt"],
      files: [
        {
          path: "registry/wuhan/examples/prompt-disabled.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/wuhan/examples/prompt-disabled.tsx"
        );
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name;
        return { default: mod.default || mod[exportName] };
      }),
      categories: undefined,
      meta: undefined,
    },
  },
};
